name: Prune Stale ROSA Roles on AWS
run-name: ROSA Role Pruner
on:
  workflow_dispatch:
    inputs:
      override:
        type: choice
        description: Bypass the anomaly check that sees if there are more than 20 clusters that are marked as nonexistent
        default: false
        options:
          - true
          - false
  schedule:
  - cron: '0 4 * * 6'
jobs:
  prune:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v3
    
    - name: Install rosa cli
      run: |
        echo $PATH
        podman run --pull=always --rm registry.ci.openshift.org/ci/rosa-aws-cli:latest cat /usr/bin/rosa > ~/rosa && chmod +x ~/rosa 
        mkdir -p ~/.local/bin
        mv ~/rosa ~/.local/bin/rosa
        rosa version

    - name: Run Script
      run: |
        rosa login --client-id $OCM_CLIENT_ID --client-secret $OCM_CLIENT_SECRET
        ./script/rosa_role_cleanup.sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ROLE_DELETE_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ROLE_DELETE_KEY }}
        OCM_CLIENT_ID: ${{ secrets.OCM_CLIENT_ID }}
        OCM_CLIENT_SECRET: ${{ secrets.OCM_CLIENT_SECRET }}
        AWS_DEFAULT_REGION: 'us-east-1'
        OVERRIDE: ${{ github.event.inputs.override }}



